const effects = [

    {
        card: "card0",
        name: "",
        artist: ["","",""],
        image: ["image0","imageB0","imageC0"],
        activeImage: 0,
        price: 0,
        description: "",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card1",
        name: "Tidy up filter",
        artist: ["Ino","Feguimel","Rain Prophet"],
        image: ["image1","imageB1","imageC1"],
        activeImage: 0,
        price: 10,
        description: "With this simple filter your photo subjects will look as clean as if they've just come out of a refreshing shower. <br>You can remove dirt, stains, sweat or iron out their clothes.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card2",
        name: "Hair and makeup filter",
        artist: ["Eymbee","Cherry-Gig","Cherry-Gig"],
        image: ["image2","imageB2","imageC2"],
        activeImage: 0,
        price: 15,
        description: "This bundle of filters will let you apply a large assortments of makeup products to your photo subjects, ranging anywhere from just a light eyeliner and lipstick to complex full face makeups. <br>You can also use it to change their haircut, be it a buzzcut, shoulder-lenght dreadlocks, waist-long pony-tail, or pretty much anything in between. You can even dye it to any color you want. <br>In case you're wondering, yes we do have separate filters for faical hair, body hair and even for pubes.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card3",
        name: "Dress up filter",
        artist: ["Amora","Carina (Xiaowoo)","Khyleri"],
        image: ["image3","imageB3","imageC3"],
        activeImage: 0,
        price: 25,
        description: "You can replace what your photo subjects are wearing with something from our ever expanding library of clothing items.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card4",
        name: "Color filter",
        artist: ["em","BlancLauz","Vero"],
        image: ["image4","imageB4","imageC4"],
        activeImage: 0,
        price: 20,
        description: "The Color filter will allow you to change your photo subjects' natural hair and skin color, to any other naturally existing variations, you can also add some ethnic characteristics to go with their changing appearance. <br>Additionally, we have sliders to adjust how tanned they are, with templates that will let you pick the type of tan-line you are looking for.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card5",
        name: "Body type filter",
        artist: ["JanRock","Bamboo Ale","Zako (Arvinry)"],
        image: ["image5","imageB5","imageC5"],
        activeImage: 0,
        price: 25,
        description: "You'll be able to adjust your photo subjects' height and body type. They can be skinny, fit, or chubby, as long as a body type exist, we probably have a filter for it.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card6",
        name: "Gender filter",
        artist: ["Yoni","Gojarun","Ripushko"],
        image: ["image6","imageB6","imageC6"],
        activeImage: 0,
        price: 30,
        description: "These filters will allow you to make anybody more feminine, or masculine.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card7",
        name: "Beauty filter",
        artist: ["Aoin","Basnip","PudgeRuffian"],
        image: ["image7","imageB7","imageC7"],
        activeImage: 0,
        price: 25,
        description: "Everyone is beautiful in their own way, but with this filter you can choose exactly which way. You can change their overall face shape, make it more symmetric, change the shape of a nose or other any other parts you're unsatisfied with.  You can also give them perfect white teeth, remove or add birthmarks, freckles, acne or anything similar.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card8",
        name: "Age filter",
        artist: ["BlancLauz","n647","Teer"],
        image: ["image8","imageB8","imageC8"],
        activeImage: 0,
        price: 30,
        description: "Have you ever wondered how your friends looked like when they were younger, or how they'll look like in ten years. Wonder no more, this filter will show you exactly that.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card9",
        name: "Picture of health filter",
        artist: ["Arkuny","Cherry-Gig","Razalor"],
        image: ["image9","imageB9","imageC9"],
        activeImage: 0,
        price: 30,
        description: "With this filter you can heal any unwanted blemishes, scars, wounds, or anything illnesses. Basically any Injury, disease or disability you could know.<br>Because nobody wants a memory tainted by being sick on an important day.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card10",
        name: "Nude filter",
        artist: ["Haidara","aaaa","Diisuke"],
        image: ["image10","imageB10","imageC10"],
        activeImage: 0,
        price: 5,
        description: "Exactly like you'd expect, this filter gives you a 99% real to life depiction of how your photo subjects would look like without clothes on.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card11",
        name: "Wet filter",
        artist: ["Yomu (sgt epper)","Versecon","Yellowroom"],
        image: ["image11","imageB11","imageC11"],
        activeImage: 0,
        price: 5,
        description: "This filter will make your photosubjects appear wet. This could appear to be because of rain, spilled liquids, mud, paint, overproduction of sexual fluids, a bathroom accident, because of spontaneous lactation, or any other reason really.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card12",
        name: "Lewd filter",
        artist: ["Doppel","Diathorn","InCase"],
        image: ["image12","imageB12","imageC12"],
        activeImage: 0,
        price: 15,
        description: "This filter is all about changing the lewd parts of your photo subjects. You can change the shape, size, or overall appearance of their genitals, or breasts.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card13",
        name: "Pet filter",
        artist: ["FaustSketcher","AuraHack","BBC-Chan"],
        image: ["image13","imageB13","imageC13"],
        activeImage: 0,
        price: 20,
        description: "Catgirls!!<br>You can give your photo subjects animal traits such as ears, tails, fangs, fur, wings. Whatever you can find or a regular animal we probably have it on offer here.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card14",
        name: "Supernatural filter",
        artist: ["LeraPi","Negarobo","Sakurai Energy"],
        image: ["image14","imageB14","imageC14"],
        activeImage: 0,
        price: 20,
        description: "This filter lets you turn your photo subjects into fictional creatures, be it demons, elves, eldrich mosters and much more.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card15",
        name: "Mirror filter",
        artist: ["Freideugoi","GaiiDraws","JCM2"],
        image: ["image15","imageB15","imageC15"],
        activeImage: 0,
        price: 30,
        description: "You can change your photo subjects to look like someone else. You are limited on what you can copy by the filters you've purchased (you need gender filter, if you want to make a man look like a woman, otherwise they'll look as a male version of the person you're trying to copy.). If you have Dress up filter, you can save any clothes your photo subjects are wearing to use on other photo subjects.",
        alternateDescription: "",
        changedByRealGameChanger: true,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card16",
        name: "Toys",
        artist: ["SushoArtwork","DekoTF","Polyle"],
        image: ["image16","imageB16","imageC16"],
        activeImage: 0,
        price: 10,
        description: "If you pick this, we'll give you a dildo and a fleshlight. Using the app, you'll be able to synchronize them with one of your photo subjects, which means the toys will change to match the shape of their respected genitals (or butt/mouth). The synchronization process takes about 20 minutes, and they can be re-synchronized any number of times. They might not be as good as the real thing, but they'll feel pretty close to it.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card17",
        name: "Living doll",
        artist: ["ShadMan","JJFrenchie","TinkerBomb"],
        image: ["image17","imageB17","imageC17"],
        activeImage: 0,
        price: 40,
        description: "If you take this, we'll give you a human sized sex doll, which similarly to the dildo and fleshlight, you can synchronize with one of your photo subjects. The synchronization process takes about 2 hours and the doll can be re-synchronized anytime you want. More than that the doll will be able to move around and follow simple instructions, and even speak, although don't expect it to say too much, after all it's still just a sex doll. <br>You can freely alter your doll's appearance using our filters",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card18",
        name: "Real game-changer",
        artist: ["R4","BlancLauz","Sulcate"],
        image: ["image18","imageB18","imageC18"],
        activeImage: 0,
        price: 100,
        description: "This is a real game-changer, you no longer just change photos, now you can transform the actual real life body of your photo subjects. This can be achieved by the use of nano-bots which inject 100% realistic syntetic flesh to implant onto your photo subject's body, in some cases they'll use other syntetic materials.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card19",
        name: "Everything checks out",
        artist: ["C.Cu","Ama Mitsuki","AuraHack"],
        image: ["image19","imageB19","imageC19"],
        activeImage: 0,
        price: 10,
        description: "This feature will ensure that any change you make to your photo subjects, will also be applied to all their id cards and licenses. This doesn't just change their photo, but will update their personal information as well, such as their height, date of birth, gender, and can even give them a new name. If you use the Mirror filter to copy someone's appearance, they can receive the copied person's identifications as well. This also makes changes to databases that store informations about your photo subjects.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "Real game-changer",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card20",
        name: "Voice changer",
        artist: ["Twinpoo","Hitomi O","Amanda Kenny"],
        image: ["image20","imageB20","imageC20"],
        activeImage: 0,
        price: 10,
        description: "You can change how your photo subjects sound like, make their voice deeper, softer, give them an accent, or if you have the Mirror filter you can even make them sound like another person of your choosing.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "Real game-changer",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card21",
        name: "Awareness options",
        artist: ["Hitomi O","Frans Mensink","Nyantcha"],
        image: ["image21","imageB21","imageC21"],
        activeImage: 0,
        price: 20,
        description: "You can decide whether your photo subjects, and the general public notice the changes you're making with our app, or they'll think changes are perfectly normal, if they even notice that something cahnged. Every time you make a change, you can apply this to the general public and each of your photo subjects seperately.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "Real game-changer",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card22",
        name: "Compatibility support",
        artist: ["X-T3AL","Combos-n-Doodles","Domovoi Lazaroth"],
        image: ["image22","imageB22","imageC22"],
        activeImage: 0,
        price: 30,
        description: "Usually our filters only work with photos taken through our app, but with this feature you can use any photo you happen to find. You can use it on a random photo you find on the internet, or you could scan a photo of a newspaper article or polaroid, as long as our app can recognize a living person on it, our filters should work with it. You might have trouble applying filters to real life if the photo subjects changed considerably since the photo was taken however, but you can still save all the changed images for yourself and share them with your friends.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card23",
        name: "Art support",
        artist: ["QueenComplex","Gela-g-i-s-Gela","Cheese-Ter"],
        image: ["image23","imageB23","imageC23"],
        activeImage: 0,
        price: 25,
        description: "You can use our filters on fictional, drawn characters. Changing them in their own art style, and you can change real life photos to look like they were drawn by your favorite artist, or in the style of your favorite anime or cartoon.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "Compatibility support",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card24",
        name: "Triggers",
        artist: ["Oshiza","Ripushko","Sulcate"],
        image: ["image24","imageB24","imageC24"],
        activeImage: 0,
        price: 20,
        description: "You can set up filters to activate on their own, when certain conditions are met. You could set the Age filter to make someone younger on their birthday, or the Health filter to heal your photo subjects immediately after they get into an accident, or you could use the Lewd filter to make someone's penis shrink every time they cheat on someone. You can set any condition you can think of as long as it can be monitored by our app. You can also use it to gradually implement changes over a set period of time.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "Real game-changer",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card25",
        name: "Video support",
        artist: ["Ninjartist","Cherry-Gig","SanePerson"],
        image: ["image25","imageB25","imageC25"],
        activeImage: 0,
        price: 15,
        description: "While usually our filters are limited to photos, you can use this feature to change videos. You could even watch entire movies with your selected filters applied to your favorite characters.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "Compatibility support",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card26",
        name: "Game support",
        artist: ["AntWolph","MenoZiriath","Nisetanaka"],
        image: ["image26","imageB26","imageC26"],
        activeImage: 0,
        price: 15,
        description: "With this feature you could change characters from computer games with our filters and play with their changed version in real time. As a bunus, you can now use a computer as a more convenient way to use our app.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "Art support",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card27",
        name: "VR support",
        artist: ["SunsetNiva","ISeeNudePeople","UgliGoth"],
        image: ["image27","imageB27","imageC27"],
        activeImage: 0,
        price: 20,
        description: "We are going to recreate your photos in a 3D space and you'll be able to look at and inspect them from different angles using your phone, or any commercially available VR headset, assuming you have one. This means you'll be able see details that aren't shown on the original picture, if it's just off screen, or blocked by another object.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "Compatibility support",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card28",
        name: "Glasses",
        artist: ["GreenTree","Kidetic","Sanuki (Kyoudashya)"],
        image: ["image28","imageB28","imageC28"],
        activeImage: 0,
        price: 15,
        description: "We'll give you a new pair of glasses, which you can use to view the world with specific filters applied to selected individuals, or it could apply the filters to everyone. You can also use the glasses to take pictures, or record videos, and if you have bad eyesight, we can customize it so you can use it as regular glasses as well.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card29",
        name: "Photogenic filter",
        artist: ["Kriminal","AntWolph","Basnip"],
        image: ["image29","imageB29","imageC29"],
        activeImage: 0,
        price: 10,
        description: "This filter will ensure that anyone you take a photo of through our app will look as good as they possibly can, no more awkward smiles, or blinking just at the wrong time. The photos will always end up depicting the best versions of your photo subjects.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card30",
        name: "Safety insurance",
        artist: ["VeryMediocre","Doppel","Qew123"],
        image: ["image30","imageB30","imageC30"],
        activeImage: 0,
        price: 20,
        description: "With this, if anyone else tries to use our app on your phone, it'll change into a blank screen, ensuring you're the only one able to use it. (You can set up exceptions if you want to share it with your friends.) Furthermore if you ever lose your phone, break it, or simply replace it, we'll install our app onto any new devices you start using. If we're sending you any additional items such as glasses or toys, with this you'll be eligible for free repairs, or replacements in case they get damaged, or go missing.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card31",
        name: "Add contact",
        artist: ["Polyle","Hoodie","JLullaby"],
        image: ["image31","imageB31","imageC31"],
        activeImage: 0,
        price: 5,
        description: "With this feature you'll be able to find any one of your photo subjects. We'll put all their contact info in your phone, this includes their full name, phone number, all their social media accounts, home address and even a location tracker for their phone. We respectfully ask our users to not use this feature for stalking, or harassing people as it is bad for publicity.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card32",
        name: "Photo history",
        artist: ["Andava","Boli-blog","SpikedMauler"],
        image: ["image32","imageB32","imageC32"],
        activeImage: 0,
        price: 25,
        description: "With this you'll be able to look at and save any photos previously taken of your photo subjects. We automatically assigns a number of tags and timestamps of when the photos were taken, in order for you to easily find the kind of photos you're looking for.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "Add contact",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card33",
        name: "Spy-cam feed",
        artist: ["BBC-Chan","Feguimel","Kantoku"],
        image: ["image33","imageB33","imageC33"],
        activeImage: 0,
        price: 25,
        description: "With this feature comes an invisible and intangible camera that will follow one of your photo subjects and gives you real time video feed straight to your phone. You can choose who the camera follows and it will only take seconds to switch between your photo subjects. You can obviously take photos, or videos through the camera. It can also send you notifications, or start recording them when they start doing certain activities. You could also just use it to take photos of yourself from a third person perspective.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "Add contact",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card34",
        name: "Invite a friend",
        artist: ["OptionalTypo","Blanclauz","IAHFY"],
        image: ["image34","imageB34","imageC34"],
        activeImage: 0,
        price: 10,
        description: "There's no better advertisment than word of mouth. You can get more credits by sharing this CYOA with someone you know.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },
    
    {
        card: "card35",
        name: "Watermark",
        artist: ["Cherry-Gig","Hjl","Khyleri"],
        image: ["image35","imageB35","imageC35"],
        activeImage: 0,
        price: 25,
        description: "If you take this, we'll put a watermark of our logo to every image you modify with our app. More than that, any photo subject you change with the Real game-changer will get a tattoo of our logo. <br>The tattoos will be removed if you disable all applied filters.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },
    
    {
        card: "card36",
        name: "Show off our goods",
        artist: ["Scas","John Doe","Sulcate"],
        image: ["image36","imageB36","imageC36"],
        activeImage: 0,
        price: 30,
        description: "You can gain a lot of extra credit by showing people what our app can do, and the best way for that is by putting yourself in the spotlight.<br> If you take this you'll have to create a social media account on a platform like Instagram or Onlyfans and show off your new improved assets there. You'll have to upload on a weekly basis and maintain at least 1000 followers for 3 years. Obviously you can keep any profit you gain from it. <br>If you fail to meet any of the requirements set out here, you'll be forced to work for us and show our investors and future customers directly what they're buying into.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card37",
        name: "Give us feedback",
        artist: ["Dash Ravo","SushoArtwork","Sunna (Nilsunna)"],
        image: ["image37","imageB37","imageC37"],
        activeImage: 0,
        price: 10,
        description: "Our app is still in development, so customer feedback is very much appreciated. <br>It can be anything from pointing out any flaws you found, to sharing your opinion about it, or just telling us what features you decided to purchase. <br>The best platform for this might just be the comment section.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },
    
    {
        card: "card38",
        name: "Consent required",
        artist: ["Ameyame","Antiomer","Himura Kiseki"],
        image: ["image38","imageB38","imageC38"],
        activeImage: 0,
        price: 20,
        description: "If you take this, before you try to transform a photosubject we'll send them a request and only make any changes to them if they agree to it, furthermore they'll have the chance to undo the changes, if they no longer want them. <br>Many people believe this shouldn't be optional, but we decided to give people bonus credits for it, we have faith in our customers and fully expect each and every one of them to take this option, proving to everyone that people using our app aren't deviants and perverts, but respectable, upstanding citizens.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "Real game-changer",
        requiresState: 1,
        requiredBy: 0
    },
    
    {
        card: "card39",
        name: "Improve our AI",
        artist: ["Melkor Mancin","Doppel","Soushiyo"],
        image: ["image39","imageB39","imageC39"],
        activeImage: 0,
        price: 25,
        description: "Nobody likes unsolicited dick pics, so we're making an AI for finding dick pics as to help people avoid them. The AI can already pick them out with exceptional efficiency, but occasionally it marks an innocent picture as a dick pic, we can't let that happen and this is where you come in. We want you to look through a batch of those images very carefully, in great detail and point out all the images without dicks in them. On average you'd have to look through 30 images a day, but you can save them up, so you'd only have to do it once a week, you only have to do this until our AI is up to our standard, which is to say a couple of years. <br>At the end of this you'll have to stay, so we can do a test run to see if you can tell those images apart, because if you can't we'll have to fix that somehow.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card40",
        name: "Bulk buyer",
        artist: ["PudgeRuffian","Ripushko","SushoArtwork"],
        image: ["image40","imageB40","imageC40"],
        activeImage: 0,
        price: 0,
        description: "We'll give you more credit, if you spend more credit, how does that sound? We'll give you 2 credit for every time you purchase all three features of a subcategory.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },
    
    {
        card: "card41",
        name: "Ads",
        artist: ["Sparrow","Erozama","TheTenk"],
        image: ["image41","imageB41","imageC41"],
        activeImage: 0,
        price: 15,
        description: "We can give you extra credits, if you let us show you ads while you're using our app. We'd show you an ad approximately every ten minutes you're actively using our app, you can skip most of them after five seconds and who knows, maybe we'll show you something you're actually interested in and turn it into a win-win.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },
    
    {
        card: "card42",
        name: "Good and charitable",
        artist: ["Angelo (Gomahangetsu)","Mosbles","UltraBondageFairy"],
        image: ["image42","imageB42","imageC42"],
        activeImage: 0,
        price: 25,
        description: "This is a reward given to people who are beyond a doubt good people. In order to prove you are a good person you'll have to donate a minimum of 15$ (in USD or its equivalent in your preferred currency) to a charity of your choice every month. <br>Or you could use that money to support a small indie developer on patreon or on any other platform.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card43",
        name: "Charging plug",
        artist: ["Andava","Chamucasdelamor69","MenoZiriath"],
        image: ["image43","imageB43","imageC43"],
        activeImage: 0,
        price: 20,
        description: "The human body is famously bad at converting food into energy, luckily we have a device that can harvest the otherwise wasted energy and use it to power our app. We'll pair you up with such a device which you'll have to insert into your rectal cavity and keep it there for about an hour before it's charged enough to power our app. The device was designed with long term use in mind and has a self cleaning function, so you could keep it equipped indefinitely. It was made to look like a traditional butt plug, to avoid embarrassing people who are caught using it, as a bonus it charges your phone as long as you have it equipped.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },
    
    {
        card: "card44",
        name: "Fluid charge",
        artist: ["MistiMagi","Jajala","VeryMediocre"],
        image: ["image44","imageB44","imageC44"],
        activeImage: 0,
        price: 25,
        description: "With this you'll need bodily fluids to use our app. <br>Our computers have to use a lot of processing power to create models of the human body, but luckily the your body could do it much more intuitively. We can modify your body to help create the models for us, you simply have to expose it to human DNA via bodily fluids. How much models you can create will depend on the type of fluid you use, the method of exposure to it and the quantity. The best suited for it are seminal fluid, breast milk and other sexual fluids, but to a lesser extent saliva, sweat and urine will also work. (don't try any other type of bodily fluids, that would be weird) Your body can get exposed to the fluids by simply covering your skin with it and let it absorb it, but it's more effective to drink it or have it directly injected into your body either anally, or vaginally. (Do not inject it into the bloodstream, again that would be weird.) A normal ejaculation worth of semen swallowed should be able to power about four transitions using our app, but if you only use it to create images you can easily get ten times as many uses out of it. If it wasn't clear you need to use other people's DNA, but if you don't have access to another person, you could use your own fluids, but don't expect to get more than one use out that, if even that much. You can store charges with no real upwards cap, but the more charge you're storing the less effective each dose will become.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },
    
    {
        card: "card45",
        name: "Plastic changes",
        artist: ["Iranon","CherryMouseStreet","Dean Yeagle"],
        image: ["image45","imageB45","imageC45"],
        activeImage: 0,
        price: 30,
        description: "The synthetic flesh we use to transorm our photo subjects is very difficult to produce, so instead we'll use much more readily available alternatives, more traditionally used in plastic surgeries. <br> The end result won't look or feel as realistic, but it'll save us a lot of resources.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "Real game-changer",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card46",
        name: "Night-time visitors",
        artist: ["Kyder","BBC-Chan","WTFeather"],
        image: ["image46","imageB46","imageC46"],
        activeImage: 0,
        price: 30,
        description: "One of our partner companies are looking for volunteers for some of their experiments, for it's duration, about once a week while you're sleeping you'll have nigthmares of getting violated by otherwordly monsters. Depending the results, the experiment could last anywhere between 6 months to three years.<br><br>Don't worry, they're only dreams... right?",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },
    
    {
        card: "card47",
        name: "Work for it",
        artist: ["InCase","John Doe","VoidNosferatu"],
        image: ["image47","imageB47","imageC47"],
        activeImage: 0,
        price: 15,
        description: "It's much easier to mold a body that is being taken care of, ideally this would require you to work out regularly, but that would be too difficult to monitor, so if you can do 500 reps of your prefered exercices, (or a total of 40 minutes of exercise) we'll give you some extra credit. <br>(If you already did this today, you can get the extra credit without further requirements)",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "Body type filter",
        requiresState: 1,
        requiredBy: 0
    },
    
    {
        card: "card48",
        name: "Trust exercise",
        artist: ["Valerie-V","Cherry-Gig","Spidu"],
        image: ["image48","imageB48","imageC48"],
        activeImage: 0,
        price: 25,
        description: "You can get more credit by simply doing what we tell you without questioning why. We simply want you to write something on your body. Can you do that for us? <br>We'll tell you what exactly at the end.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },

    {
        card: "card49",
        name: "Lewd clothes",
        artist: ["Tenguro","Rucchiifu","MarmaladeMum"],
        image: ["image49","imageB49","imageC49"],
        activeImage: 0,
        price: 25,
        description: "Our Dress up filter has a new version developed by one of our subsidiary companies that needs further testing. If you're willing to take part in the testing you'll be awarded with some extra credit, but you should be aware of a few known issues. Unbeknown to us they used a large amount of softcore pornoghraphic material as reference in developing this filter, as a result you should expect the garments to be either tight fitting, show a lot of cleavage, be see-through, lack underwear, bring attention to bulges, or have other unexpected wardrobe malfunctions or lewd side effects. <br>Furthermore it can spontaneously activate itself on any of your photo subjects, even if you haven't purchased Real game-changer.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "Dress up filter",
        requiresState: 1,
        requiredBy: 0
    },
    
    {
        card: "card50",
        name: "Pet friends",
        artist: ["Don3","BarleyShake","NinjaKitty"],
        image: ["image50","imageB50","imageC50"],
        activeImage: 0,
        price: 20,
        description: "As a side effect, the Pet filter will modify your body to release pheromones that'll make pets and animals become much more friendly towards you, expect to get approached on a daily basis, asking you to pet them. You should also expect them to occasionally try to take your clothes off, not for any perverted reasons, they just want to have as much skin to skin (skin to fur?) contact with you as they can get. <br>This change will also get applied to the photo subjects you transform with the Pet filter.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "Pet filter",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card51",
        name: "Prescription glasses",
        artist: ["AlexisFlower","Gerph","LaekaBear"],
        image: ["image51","imageB51","imageC51"],
        activeImage: 0,
        price: 30,
        description: "So the glasses we give you... from now on you'll need them to see. I mean why use your brain to process images, when the glasses can do it for you?! When you don't wear them you'll only be able to see general shapes and blurred colors, but thanks to a small tracking device you'll always instinctively know where you left your glasses.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "Glasses",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card52",
        name: "Pleasurable changes",
        artist: ["A.X.","Ordnance","Sulcate"],
        image: ["image52","imageB52","imageC52"],
        activeImage: 0,
        price: 15,
        description: "Transforming someone's body is a very intrusive process. It can be a confusing and often frightening experience, even when our photo suject are expecting the change. <br>This is why developed a method that would activate the body's natural pleasure receptors, both distracting the photo subject from the transformation process and ensuring that they'll associate the experience with something positive. <br><br>Warning: This can cause uncontrollable orgasms and as such, we recomend finding a safe, private space before every transition.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "Real game-changer",
        requiresState: 1,
        requiredBy: 0
    },
    
    {
        card: "card53",
        name: "They can see through you",
        artist: ["Hitomi O","Rucchiifu","Spacenipnops"],
        image: ["image53","imageB53","imageC53"],
        activeImage: 0,
        price: 25,
        description: "Some people will see you for who you really are. <br>It's as if they'd have a filter active that cancels out all active filter for you. It'll be very rare, only about one in five hundred people have this, but you'll have no way of telling who they are. They'll also instinctively know your intentions, and can tell if you lie to them.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "Real game-changer",
        requiresState: 1,
        requiredBy: 0
    },
    
    {
        card: "card54",
        name: "Useless member",
        artist: ["Parkdale","MarmaladeMum","VoidNosferatu"],
        image: ["image54","imageB54","imageC54"],
        activeImage: 0,
        price: 50,
        description: "Modifying reproductive systems and genitals is a real pain in the butt, but if you take this we won't have to deal with that anymore. <br>We'll replace whatever you have with a mass produced 3 inch penis that is infertile and can't even get completely erect, you'll still feel pleasure and will be capable of having orgasms. <br><br>You'll be unable to alter it with any of our filters.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "Real game-changer",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card55",
        name: "Censored",
        artist: ["Emmanuel Viola","Nagainosfw","D-rex"],
        image: ["image55","imageB55","imageC55"],
        activeImage: 0,
        price: 30,
        description: "Not that you'd ever do that, but some people use our app to satisfy their perverted curiosities, and some people think it's bad for our public image, so if you agree to let us install a parental supervision software that will censor all nudity (with a 98% success rate) on every electronic device you use, we'll give you some extra credit for you to spend. (If you start using a new device we'll automatically install it on that too)",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },
    
    {
        card: "card56",
        name: "Censored (only women)",
        artist: ["Mare Ten","LewdishSnail","LewdishSnail"],
        image: ["image56","imageB56","imageC56"],
        activeImage: 0,
        price: 10,
        description: "There is a version of the parental supervision program that only censors female nudity, and for a small price you can have this version installed instead. <br>I know it feels like a double standard, but for some reason our investors aren't as upset with the exploitation of men.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: false,
        state: 0,
        requires: "Censored",
        requiresState: 1,
        requiredBy: 0
    },
    
    {
        card: "card57",
        name: "Censored (real life)",
        artist: ["Emmanuel Viola","Gao-Lukchup","Inamitsu Shinji"],
        image: ["image57","imageB57","imageC57"],
        activeImage: 0,
        price: 50,
        description: "Some people find this a bit extreme, but we can install the parental supervision program directly into your brain, making you unable to perceive nudity in real life. <br>Don't worry the process is 99.8% safe, the only known issue is that it needs to install updates on a monthly basis and when it happens you won't have any protection against indecency for about 3 hours. Don't worry, we'll notify you beforehand, so you can avoid exposure to anything lewd.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "Censored",
        requiresState: 1,
        requiredBy: 0
    },

    {
        card: "card58",
        name: "Send nudes",
        artist: ["BlancLauz","GaiiDraws","Izra"],
        image: ["image58","imageB58","imageC58"],
        activeImage: 0,
        price: 1,
        description: "Our AI already uses an expansive lirbrary of reference images in order to make our app work, but it can always benefit from further expansion. <br> This is where you come in, by sending us reference images of your own body you can gain a small amount of credit with our company.<br><br>... That is the whole reason, it's definitely not for my perverted personal use.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },
    
    {
        card: "card59",
        name: "Give me a hug",
        artist: ["Robin Haver","Zako (Arvinry)","Antiomer"],
        image: ["image59","imageB59","imageC59"],
        activeImage: 0,
        price: 20,
        description: "Hugs are good, so credit... <br> <br>I don't actually have anything for here, I've just been feeling pretty down lately and could really use a hug, so if you promise to give me one (in the unlikely event that we actually meet), I'll give you some credits.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    },
    
    {
        card: "card60",
        name: "True form",
        artist: ["Matilda Fiship","Matilda Fiship","Matilda Fiship"],
        image: ["image60","imageB60","imageC60"],
        activeImage: 0,
        price: 25,
        description: "If you take this, you'll be turned into your true form, which is obviously a cute potato. <br>You can still change your appearance using our app, (assuming you purchased the appropriate filters) but one night each month you will change back to your true form and you won't be able to change again for a full 24 hours.",
        alternateDescription: "",
        changedByRealGameChanger: false,
        drawback: true,
        state: 0,
        requires: "",
        requiresState: 0,
        requiredBy: 0
    }

]