let bonuses = {
    permanent: 0,
    heart: 0,
    pic: 0,
    picKeep: 0,
    picSend: 0,
    picShare: 0,
    double: 0,
};

let writeLocation = [
    "Anywhere on your body",
    "Chest",
    "Upper arm",
    "Forearm",
    "Hand",
    "Stomach",
    "Upper back",
    "Inner thigh",
    "Thigh",
    "Calves",
    "Feet",
    "Ankles",
    "Wrist",
    "Neck",
    "Lower back",
    "Face",
    "Butt",
    "Under armpit",
    "Around your nipples",
    "Forehead",
    "Above your crotch",
];
let write = [
    "Slut",
    "Cumslut",
    "Daddy",
    "Whore",
    "Fucktoy",
    "Breed me",
    "Free use",
    "Rape me daddy",
    "Rape toy",
    "Sex doll",
    "I love cock",
    "Sex addict",
    "Slave",
    "Spank me",
    "Choke me daddy",
    "Humiliate me",
    "Punish me",
    "Expose me",
    "Make me regret this",
    "Use me",
    "Worthless",
    "I'm beautiful",
    "I love myself",
    "I wanna hold your hand",
    "Free cuddles",
    "The name of someone you're attracted to",
    "I wanna be your dog",
    "Make me scream",
    "Do you think I'm pretty?",
    "Are proud of me dad?",
    "Look mom, I'm famous",
    "Horse dicks are kinda attractive",
    "$4.99",
    "I give blowjobs for compliments",
    "Spit in my mouth",
    "I worship dicks",
    "Cum here",
    "Cum in my hair",
    "I have low self esteem",
    "Bitch",
    "I'm an idiot",
    "Dumb bitch",
    "Can I be your maid?",
    "Bimbo",
    "Please love me",
    "Stalk me",
    "Piss on me",
    "Human toilet",
    "Hurt me",
    "Beat me up",
    "Bully me",
    "Webslut",
    "Grope me in public",
    "Pain slut",
    "Blackmail me",
    "Destroy me",
    "You can call me mommy",
    "Suck me dry",
    "Milk me",
    "Hot stuff",
    "Bitch in heat",
    "Feed me cum",
    "Would you adopt me?",
    "Snack",
    "I deserve this",
    "Kiss me",
    "Spit on me",
    "Wanna shower together?",
    "Worship me",
    "Handle with care",
    "Fragile",
    "Delicate",
    "Traumatize me",
    "Can I lick your feet?",
    "Lock me up",
    "Collar me",
    "Spank me",
    "Touch me",
    "Am I a freak?",
    "Sit on my face",
    "Can I sit on your face?",
    "Can I give you a rimjob?",
    "Take a hint"
]